version: '3'
services:
  db-booking:
    container_name: db-booking
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5431:5432"  # Mapea el puerto 5432 del contenedor al puerto 5431 del host

  db-inventory:
    container_name: db-inventory
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5434:5432"  # Mapea el puerto 5432 del contenedor al puerto 5434 del host

  db-payment:
    container_name: db-payment
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_payment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"  # Mapea el puerto 5432 del contenedor al puerto 5433 del host

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"